spring:
  profiles:
    active: local
    jdbc:
      initialize-schema: ALWAYS
  web:
    resources:
      cache:
        period: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'hyungjookim12@gmail.com'
    password: 'zdmhriwdshbywafe'
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3320/deploy_test?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7008